name: Playwright Tests in Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run tests in container
        run: docker run --rm playwright-tests

      - name: Generate Allure HTML Report
        run: npm run allure-generate

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure Raw Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
