name: Playwright Tests in Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run tests in container and copy allure-results
        if: always()
        run: |
          docker create --name testcontainer playwright-tests
          docker start -a testcontainer
          docker cp testcontainer:/app/allure-results ./allure-results
          docker rm testcontainer

      - name: Install Allure CLI on runner
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Allure HTML Report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure Raw Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
